#! /bin/sh

bspc config border_width        0
bspc config window_gap         12

bspc config top_padding        15

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9

python -O ~/.config/bspwm/bar.pyc | bar -p -B "#E62A2A2A" -f "-xos4-terminus-medium-r-normal--12-120-72-72-c-60-iso10646-1,-misc-stlarch-medium-r-normal--10-100-75-75-c-80-iso10646-1" &

compton -cb
feh --bg-scale ~/Pictures/Wallpapers/41\ \-\ w7eDZe6.jpg &
