theme = "gruvbox"

[editor]
bufferline = "always"
color-modes = true
cursorline = true
end-of-line-diagnostics = "hint"
true-color = true
trim-final-newlines = true
trim-trailing-whitespace = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
tab = "→"
tabpad = "·"

[keys.normal]
tab = ":buffer-next"
S-tab = ":buffer-previous"
C-b = ":sh git blame --incremental -L %{cursor_line},+1 %{buffer_name} | head -n 1 | cut -d ' ' -f 1 | xargs git show"
