# SCLS offers word completion based on current buffer's contents
[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 100           # set max completion results len for each group: words, snippets, unicode-input
feature_words = true                 # enable completion by word
feature_snippets = true              # enable snippets
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_unicode_input = false        # enable "unicode input"
feature_paths = false                # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)

# Harper offers grammar and spell checking
[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[[language]]
name = "git-commit"
language-servers = [ "scls", "harper-ls" ]

[[language]]
name = "dart"
scope = "source.dart"
file-types = ["dart"]
roots = ["pubspec.yaml"]
auto-format = true
comment-tokens = ["//", "///"]
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = [ "dart", "harper-ls" ]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "rust"
rulers = [100]

[[language]]
name = "markdown"
language-servers = ["harper-ls"]
